// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Backend Team",
            "email": "backend@yourcompany.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/weights": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get heuristic configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Update heuristic configuration",
                "parameters": [
                    {
                        "description": "New heuristic weights",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/create-room": {
            "post": {
                "description": "Create a new room with a single human player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Create new room",
                "parameters": [
                    {
                        "description": "Player info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/move": {
            "post": {
                "description": "Submit coordinates (x, y) and card value for player's move",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Player makes a move",
                "parameters": [
                    {
                        "description": "Move data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.MoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/move-bot": {
            "post": {
                "description": "Bot picks the best move using heuristic evaluation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Let bot make its move",
                "parameters": [
                    {
                        "description": "Bot move",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.MoveBotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/play": {
            "post": {
                "description": "Initialize bots to start the game (default 1 bot if not specified)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Add bots to a room",
                "parameters": [
                    {
                        "description": "Room info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PlayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/possible-moves": {
            "get": {
                "description": "Returns all available cells for a player's move (place/replace)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Get possible move boxes for player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room Code",
                        "name": "roomCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/set-hands": {
            "post": {
                "description": "Apply shuffled hands from FE to room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Set player hands (cards) manually",
                "parameters": [
                    {
                        "description": "Hands data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.SetHandsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.CreateRoomRequest": {
            "type": "object",
            "properties": {
                "playerName": {
                    "type": "string"
                }
            }
        },
        "http.MoveBotRequest": {
            "type": "object",
            "properties": {
                "botId": {
                    "type": "string"
                },
                "holdCards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "roomCode": {
                    "type": "string"
                }
            }
        },
        "http.MoveRequest": {
            "type": "object",
            "properties": {
                "playerId": {
                    "type": "string"
                },
                "roomCode": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                },
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "http.PlayRequest": {
            "type": "object",
            "properties": {
                "bots": {
                    "type": "integer"
                },
                "roomCode": {
                    "type": "string"
                }
            }
        },
        "http.PlayerHand": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "playerId": {
                    "type": "string"
                }
            }
        },
        "http.SetHandsRequest": {
            "type": "object",
            "properties": {
                "hands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.PlayerHand"
                    }
                },
                "roomCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Javanese Chess Bot API",
	Description:      "REST API for heuristic-based chess-like bot (Go + Gin)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
