// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Backend Team",
            "email": "backend@yourcompany.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/weights/default": {
            "get": {
                "description": "Returns the default heuristic weights based on research paper (Section 2.4)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get default heuristic weights",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/weights/room": {
            "get": {
                "description": "Returns the heuristic weights configured for a specific room",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get room heuristic weights",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room Code",
                        "name": "roomCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Updates the heuristic weights for all bots in a specific room. Weights must be non-negative.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Update room heuristic weights",
                "parameters": [
                    {
                        "description": "Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.UpdateRoomWeightsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/weights/room/reset": {
            "post": {
                "description": "Resets a room's heuristic weights to the global defaults from research paper",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Reset room weights to default",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room Code",
                        "name": "roomCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/create-room": {
            "post": {
                "description": "Create a new room with a single human player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Create new room",
                "parameters": [
                    {
                        "description": "Player info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/move": {
            "post": {
                "description": "Submit coordinates (x, y) and card value for player's move",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Player makes a move",
                "parameters": [
                    {
                        "description": "Move data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.MoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/move-bot": {
            "post": {
                "description": "Bot picks the best move using heuristic evaluation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Let bot make its move",
                "parameters": [
                    {
                        "description": "Bot move",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.MoveBotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/play": {
            "post": {
                "description": "Initialize bots to start the game (default 1 bot if not specified)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Add bots to a room",
                "parameters": [
                    {
                        "description": "Room info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PlayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/possible-moves": {
            "get": {
                "description": "Returns all available cells for a player's move (place/replace)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Get possible move boxes for player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room Code",
                        "name": "roomCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/set-hands": {
            "post": {
                "description": "Apply shuffled hands from FE to room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Set player hands (cards) manually",
                "parameters": [
                    {
                        "description": "Hands data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.SetHandsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.HeuristicWeights": {
            "type": "object",
            "properties": {
                "w_block_path": {
                    "description": "W₄: Blocking enemy paths (cutting opponent lines)",
                    "type": "integer"
                },
                "w_build_alignment": {
                    "description": "W₅: Building own alignments (2 or 3 in a row)",
                    "type": "integer"
                },
                "w_card_cost": {
                    "description": "W₆: Card value management (resource efficiency)",
                    "type": "integer"
                },
                "w_replace_value": {
                    "description": "W₃: Overwriting opponent cards (strategic replacement)",
                    "type": "integer"
                },
                "w_threat": {
                    "description": "W₂: Blocking opponent's immediate threat (3-in-a-row)",
                    "type": "integer"
                },
                "w_win": {
                    "description": "W₁: Winning move detection (4-in-a-row)",
                    "type": "integer"
                }
            }
        },
        "http.CreateRoomRequest": {
            "type": "object",
            "properties": {
                "playerName": {
                    "type": "string"
                }
            }
        },
        "http.MoveBotRequest": {
            "type": "object",
            "properties": {
                "botId": {
                    "type": "string"
                },
                "holdCards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "roomCode": {
                    "type": "string"
                }
            }
        },
        "http.MoveRequest": {
            "type": "object",
            "properties": {
                "playerId": {
                    "type": "string"
                },
                "roomCode": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                },
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "http.PlayRequest": {
            "type": "object",
            "properties": {
                "bots": {
                    "type": "integer"
                },
                "roomCode": {
                    "type": "string"
                }
            }
        },
        "http.PlayerHand": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "playerId": {
                    "type": "string"
                }
            }
        },
        "http.SetHandsRequest": {
            "type": "object",
            "properties": {
                "hands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.PlayerHand"
                    }
                },
                "roomCode": {
                    "type": "string"
                }
            }
        },
        "http.UpdateRoomWeightsRequest": {
            "type": "object",
            "required": [
                "room_code",
                "weights"
            ],
            "properties": {
                "room_code": {
                    "type": "string"
                },
                "weights": {
                    "$ref": "#/definitions/config.HeuristicWeights"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Javanese Chess Bot API",
	Description:      "REST API for heuristic-based chess-like bot (Go + Gin)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
